## Random forest lab and case regression

In [24]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)

from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import neighbors

from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.model_selection import cross_val_score

In [26]:

import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

#import dataset
numerical = pd.read_csv(r'C:\Users\Administrator\Desktop\IH-Labs\week7\lab-random-forests\files_for_lab/numerical.csv')
categorical = pd.read_csv(r'C:\Users\Administrator\Desktop\IH-Labs\week7\lab-random-forests\files_for_lab/categorical.csv')
target = pd.read_csv(r'C:\Users\Administrator\Desktop\IH-Labs\week7\lab-random-forests\files_for_lab/target.csv')
X = pd.concat([numerical,categorical], axis = 1)


In [27]:
X.head()

TCODE        AGE  INCOME  WEALTH1  HIT  MALEMILI  MALEVET  VIETVETS  \
0      0  60.000000       5        9    0         0       39        34   
1      1  46.000000       6        9   16         0       15        55   
2      1  61.611649       3        1    2         0       20        29   
3      0  70.000000       1        4    2         0       23        14   
4      0  78.000000       3        2   60         1       28         9   

   WWIIVETS  LOCALGOV  STATEGOV  FEDGOV  WEALTH2  POP901  POP902  POP903  \
0        18        10         2       1        5     992     264     332   
1        11         6         2       1        9    3611     940     998   
2        33         6         8       1        1    7001    2040    2669   
3        31         3         0       3        0     640     160     219   
4        53        26         3       2        9    2520     627     761   

   POP90C1  POP90C2  POP90C3  POP90C4  POP90C5  ETH1  ETH2  ETH3  ETH4  ETH5  \
0        0       35       65       47       53    92     1     0     0    11   
1       99        0        0       50       50    67     0     0    31     6   
2        0        2       98       49       51    96     2     0     0     2   
3        0        8       92       54       46    61     0     0    11    32   
4       99        0        0       46       54     2    98     0     0     1   

   ETH6  ETH7  ETH8  ETH9  ETH10  ETH11  ETH12  ETH13  ETH14  ETH15  ETH16  \
0     0     0     0     0      0      0      0     11      0      0      0   
1     4     2     6     4     14      0      0      2      0      1      4   
2     0     0     0     0      0      0      0      2      0      0      0   
3     6     2     0     0      0      0      0     31      0      0      1   
4     0     0     0     0      0      0      0      0      0      0      0   

   AGE901  AGE902  AGE903  AGE904  AGE905  AGE906  AGE907  CHIL1  CHIL2  \
0      39      48      51      40      50      54      25     31     42   
1      34      41      43      32      42      45      32     33     46   
2      35      43      46      37      45      49      23     35     40   
3      32      40      44      34      43      47      25     45     35   
4      33      45      50      36      46      50      27     34     43   

   CHIL3  AGEC1  AGEC2  AGEC3  AGEC4  AGEC5  AGEC6  AGEC7  CHILC1  CHILC2  \
0     27     11     14     18     17     13     11     15      12      11   
1     21     13     14     33     23     10      4      2      11      16   
2     25     13     20     19     16     13     10      8      15      14   
3     20     15     25     17     17     12      7      7      20      17   
4     23     14     21     13     15     20     12      5      13      15   

   CHILC3  CHILC4  CHILC5  HHAGE1  HHAGE2  HHAGE3  HHN1  HHN2  HHN3  HHN4  \
0      34      25      18      26      10      23    18    33    49    28   
1      36      22      15      12       1       5     4    21    75    55   
2      30      22      19      25      10      23    21    35    44    22   
3      30      14      19      25      11      23    23    27    50    30   
4      34      19      19      31       7      27    16    26    57    36   

   HHN5  HHN6  MARR1  MARR2  MARR3  MARR4  HHP1  HHP2  DW1  DW2  DW3  DW4  \
0    12     4     61      7     12     19   198   276   97   95    2    2   
1    23     9     69      4      3     24   317   360   99   99    0    0   
2     6     2     63      9      9     19   183   254   69   69    1    6   
3    15     8     63      9      6     23   199   283   85   83    3    4   
4    24    14     42     17      9     33   235   323   99   98    0    0   

   DW5  DW6  DW7  DW8  DW9   HV1   HV2  HV3  HV4  HU1  HU2  HU3  HU4  HU5  \
0    0    0    7    7    0   479   635    3    2   86   14   96    4    7   
1    0    0    0    0    0  5468  5218   12   10   96    4   97    3    9   
2    5    3    3    3    0   497   546    2    1   78   22   93    7   18   
3  

In [28]:
#X & Y split

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, target.drop('TARGET_D', axis = 1), test_size=0.2)

In [30]:
#num cat_split

In [31]:
train_num  = X_train.select_dtypes(include = np.number)
train_cat = X_train.select_dtypes(include = object)

test_num  = X_test.select_dtypes(include = np.number)
test_cat = X_test.select_dtypes(include = object)

In [32]:
#scaling
from sklearn.preprocessing import MinMaxScaler
# Fitting scaler
transformer = MinMaxScaler().fit(train_num)
# Scaling train and test data
train_num_scaled = pd.DataFrame(transformer.transform(train_num), columns = train_num.columns, index = train_num.index)
test_num_scaled = pd.DataFrame(transformer.transform(test_num), columns = test_num.columns, index = test_num.index)

In [33]:
#encoding
from sklearn.preprocessing import OneHotEncoder
# Fit encoder
encoder = OneHotEncoder(handle_unknown='ignore').fit(train_cat)
# Getting the column names for the later selection
column_name = encoder.get_feature_names_out(train_cat.columns)
# Encode train and test
train_encoded = pd.DataFrame(encoder.transform(train_cat).toarray(),columns = column_name, index=train_cat.index)
test_encoded = pd.DataFrame(encoder.transform(test_cat).toarray(),columns = column_name, index=test_cat.index)

In [34]:
#oversampling
#concatening
train_all = pd.concat([train_encoded, train_num_scaled, y_train['TARGET_B']], axis = 1)
X_test = pd.concat([test_encoded,test_num_scaled], axis = 1)

In [35]:
#upscaling

In [37]:
from sklearn.utils import resample
# Splitting into majority and minority class, the 'yes' donors are the minority class.
no = train_all[train_all['TARGET_B']==0]
yes = train_all[train_all['TARGET_B']==1]

In [38]:
# oversample minority
yes_oversampled = resample(yes, #<- sample from here
                                    replace=True, #<- we need replacement, since we don't have enough data otherwise
                                    n_samples = len(no),#<- make both sets the same size
                                    )

In [39]:
# Concatenate with majority class
train_oversampled = pd.concat([no,yes_oversampled],axis=0)

In [40]:
# X-y Split again
X_train_over = train_oversampled.drop('TARGET_B', axis = 1)
y_train_over = train_oversampled['TARGET_B']

In [41]:
## Randomforest

In [42]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

In [43]:
# Defining the classifier
clf = RandomForestClassifier(max_depth=5)

In [44]:
def model_eval(model,X_train,y_train,X_test, y_test):
        # Fitting
        model.fit(X_train, y_train)
        # Predicting
        predictions = model.predict(X_test)
        # Calculating confusion matrix
        cm = confusion_matrix(y_test, predictions)
        # Printing different evaluation metrics
        print( str(model.base_estimator_)[:-2] + " score: ", model.score(X_test, y_test))
        print( str(model.base_estimator_)[:-2] + " precision: ",precision_score(y_test,predictions))
        print( str(model.base_estimator_)[:-2] + " recall: ",recall_score(y_test,predictions))
        print( str(model.base_estimator_)[:-2] + " f1: ",f1_score(y_test,predictions))
        print('\n')
        print(cm)
        return model

In [45]:
model_eval(clf,X_train_over,y_train_over,X_test, y_test)

DecisionTreeClassifier score:  0.6111722475501755
DecisionTreeClassifier precision:  0.0702079745661677
DecisionTreeClassifier recall:  0.569280343716434
DecisionTreeClassifier f1:  0.125


[[11133  7019]
 [  401   530]]


RandomForestClassifier(max_depth=5)

In [46]:
from sklearn.feature_selection import VarianceThreshold 
# set threshhold
sel = VarianceThreshold(threshold= 0.02)

In [47]:
# Fitting with our numericals
sel = sel.fit(train_num_scaled)

In [48]:
# Check wich columns have low variance
sel.get_support()
# Making it a list
var_list = list(sel.get_support())
# Creating a droplist
droplist_var = [col[0] for col in zip(train_num_scaled.columns, var_list) if col[1] == False]
print(droplist_var)
len(droplist_var)

['TCODE', 'HIT', 'MALEMILI', 'MALEVET', 'LOCALGOV', 'STATEGOV', 'FEDGOV', 'POP901', 'POP902', 'POP903', 'POP90C4', 'POP90C5', 'ETH3', 'ETH4', 'ETH5', 'ETH6', 'ETH7', 'ETH8', 'ETH9', 'ETH10', 'ETH11', 'ETH12', 'ETH13', 'ETH14', 'ETH15', 'ETH16', 'AGE901', 'AGE902', 'AGE903', 'AGE904', 'AGE905', 'AGE906', 'AGE907', 'CHIL1', 'CHIL2', 'CHIL3', 'AGEC1', 'AGEC2', 'AGEC3', 'AGEC4', 'AGEC5', 'AGEC6', 'AGEC7', 'CHILC1', 'CHILC2', 'CHILC3', 'CHILC4', 'CHILC5', 'HHAGE1', 'HHAGE2', 'HHAGE3', 'HHN1', 'HHN2', 'HHN4', 'HHN5', 'HHN6', 'MARR1', 'MARR2', 'MARR3', 'MARR4', 'HHP1', 'HHP2', 'DW3', 'DW7', 'DW8', 'DW9', 'HU3', 'HU4', 'HHD1', 'HHD4', 'HHD6', 'HHD7', 'HHD8', 'HHD9', 'HHD10', 'HHD11', 'HHD12', 'ETHC1', 'ETHC3', 'ETHC4', 'ETHC5', 'ETHC6', 'HUR1', 'RHP1', 'RHP2', 'RHP3', 'RHP4', 'HUPA1', 'HUPA4', 'HUPA5', 'HUPA7', 'DMA', 'IC1', 'IC2', 'IC3', 'IC4', 'IC5', 'IC7', 'IC8', 'IC9', 'IC10', 'IC11', 'IC12', 'IC13', 'IC14', 'IC15', 'IC16', 'IC17', 'IC18', 'IC19', 'IC20', 'IC21', 'IC22', 'IC23', 'HHAS1', '

240

In [49]:
# Trying our model without the low variance columns:
model_eval(clf,X_train_over.drop(droplist_var, axis = 1),y_train_over,X_test.drop(droplist_var, axis = 1), y_test)

DecisionTreeClassifier score:  0.6182990095896872
DecisionTreeClassifier precision:  0.07253397927600592
DecisionTreeClassifier recall:  0.5789473684210527
DecisionTreeClassifier f1:  0.12891652714661567


[[11260  6892]
 [  392   539]]


RandomForestClassifier(max_depth=5)

In [50]:
%%time

from sklearn.feature_selection import RFE
from sklearn import linear_model
# Creating RFE model with Randomforest as Estimator
rfe = RFE(clf, n_features_to_select=20, verbose=False)

# Fitting
rfe.fit(train_all.drop(droplist_var, axis = 1), y_train.values.ravel())

Wall time: 10min 2s


RFE(estimator=RandomForestClassifier(max_depth=5), n_features_to_select=20,
    verbose=False)

In [51]:
import pickle
pickle.dump(rfe, open('rfe.p', 'wb'))

In [52]:
rfe_l = pickle.load(open('rfe.p','rb'))

In [53]:
rfe_l

RFE(estimator=RandomForestClassifier(max_depth=5), n_features_to_select=20,
    verbose=False)

In [54]:
# Checking Ranking of columns
df = pd.DataFrame(data = rfe_l.ranking_, columns=['Rank'])
df['Column_name'] = pd.DataFrame(train_all.drop(droplist_var, axis = 1)).columns
df = df[df['Column_name'] != 'TARGET_B']
df.sort_values(by = ['Rank'], ascending = False).head(20)

Rank  Column_name
9     103     STATE_WA
25    102   GEOCODE2_D
24    101   GEOCODE2_C
12    100   HOMEOWNR_H
107    99     HPHONE_D
26     98   DOMAIN_A_C
2      97     STATE_GA
17     96     RFA_2R_L
27     95   DOMAIN_A_R
30     94   DOMAIN_A_U
3      93     STATE_IL
1      92     STATE_FL
4      91     STATE_IN
5      90     STATE_MI
0      89     STATE_CA
29     88   DOMAIN_A_T
6      87     STATE_MO
10     86     STATE_WI
8      85     STATE_TX
11     84  STATE_other

In [55]:
for r in range(1,20,4):
    droplist_rfe = list(df[df['Rank'] < r]['Column_name'])
    droplist_full = droplist_var
    droplist_full.extend(droplist_rfe)
    # Creating dataframes without the eliminated columns
    temp_train = X_train_over.drop(droplist_full, axis = 1).copy()
    temp_test = X_test.drop(droplist_full, axis = 1).copy()
    
    # Checking results:
    print('\n\n\n Testing with columns ranking higher than ' +str(r))
    model_eval(clf,temp_train,y_train_over,temp_test, y_test)




 Testing with columns ranking higher than 1
DecisionTreeClassifier score:  0.6162553057695331
DecisionTreeClassifier precision:  0.07226980728051392
DecisionTreeClassifier recall:  0.5800214822771214
DecisionTreeClassifier f1:  0.12852552659764369


[[11220  6932]
 [  391   540]]



 Testing with columns ranking higher than 5
DecisionTreeClassifier score:  0.5524812660483153
DecisionTreeClassifier precision:  0.058181395888979213
DecisionTreeClassifier recall:  0.5381310418904404
DecisionTreeClassifier f1:  0.10500943198490882


[[10042  8110]
 [  430   501]]



 Testing with columns ranking higher than 9
DecisionTreeClassifier score:  0.5642194623486874
DecisionTreeClassifier precision:  0.057943253920747034
DecisionTreeClassifier recall:  0.5198711063372717
DecisionTreeClassifier f1:  0.10426540284360189


[[10283  7869]
 [  447   484]]



 Testing with columns ranking higher than 13
DecisionTreeClassifier score:  0.5695121312162658
DecisionTreeClassifier precision:  0.05389514943

In [60]:
#final model
final_model = clf.fit(temp_train, y_train_over)               

In [61]:
numerical  = X.select_dtypes(include = np.number)
categorical = X.select_dtypes(include = object)

In [62]:
#scalling
num_scaled = pd.DataFrame(transformer.transform(numerical), columns = train_num.columns, index = numerical.index)

In [63]:
#encoding
encoded = pd.DataFrame(encoder.transform(categorical).toarray(),columns = column_name, index=categorical.index)

In [64]:
#concatening
X_all = pd.concat([encoded,num_scaled], axis = 1)

In [65]:
#Dropping column
X_all_selected = X_all.drop(droplist_full,axis = 1)

In [66]:
#predicting
X['predicted_donate'] = clf.predict(X_all_selected)

In [67]:
clf.predict(X_all_selected)

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [68]:
#Evaluating:
predictions = clf.predict(X_all_selected)
# Calculating confusion matrix
cm = confusion_matrix(target['TARGET_B'], predictions)
# Printing different evaluation metrics
print( str(clf.base_estimator_)[:-2] + " score: ", clf.score(X_all_selected, target['TARGET_B']))
print( str(clf.base_estimator_)[:-2] + " precision: ",precision_score(target['TARGET_B'],predictions))
print( str(clf.base_estimator_)[:-2] + " recall: ",recall_score(target['TARGET_B'],predictions))
print( str(clf.base_estimator_)[:-2] + " f1: ",f1_score(target['TARGET_B'],predictions))
cm

DecisionTreeClassifier score:  0.5855447952039575
DecisionTreeClassifier precision:  0.070223675410567
DecisionTreeClassifier recall:  0.585380962213504
DecisionTreeClassifier f1:  0.1254036360419339


array([[53033, 37536],
       [ 2008,  2835]], dtype=int64)

In [69]:
df_all = pd.concat([X,target], axis = 1)

## Case Regression

In [ ]:
#Only look at people who have donated (Target B = 1)

In [72]:
# Dataframe for building the model
df_regr_build = df_all[df_all['TARGET_B']==1]
# Dataframe for making predictions
df_regr_pred = df_all[df_all['predicted_donate']==1]

In [73]:
#X-Y split

In [74]:
X = df_regr_build.drop(['TARGET_D', 'TARGET_B', 'predicted_donate'], axis = 1)
y = df_regr_build['TARGET_D']

In [75]:
#train test split

In [77]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [78]:
#Num-Cat Split

In [79]:
train_num  = X_train.select_dtypes(include = np.number)
train_cat = X_train.select_dtypes(include = object)

test_num  = X_test.select_dtypes(include = np.number)
test_cat = X_test.select_dtypes(include = object)

In [80]:
#scaling
from sklearn.preprocessing import MinMaxScaler
# Fitting scaler
transformer = MinMaxScaler().fit(train_num)
# Scaling train and test data
train_num_scaled = pd.DataFrame(transformer.transform(train_num), columns = train_num.columns, index = train_num.index)
test_num_scaled = pd.DataFrame(transformer.transform(test_num), columns = test_num.columns, index = test_num.index)

In [81]:
#Encoding
from sklearn.preprocessing import OneHotEncoder
# Fit encoder
encoder = OneHotEncoder(handle_unknown='ignore').fit(train_cat)
# Getting the column names for the later selection
column_name = encoder.get_feature_names_out(train_cat.columns)
# Encode train and test
train_encoded = pd.DataFrame(encoder.transform(train_cat).toarray(),columns = column_name, index=train_cat.index)
test_encoded = pd.DataFrame(encoder.transform(test_cat).toarray(),columns = column_name, index=test_cat.index)

In [82]:
#concating
train_encoded = pd.concat([train_encoded,train_num_scaled], axis = 1)
test_encoded = pd.concat([test_encoded,test_num_scaled], axis = 1)

In [85]:
#first model
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [86]:
def model_eval_regression(model,X_train,y_train,X_test, y_test):
        # Fitting
        model.fit(X_train, y_train)
        # Predicting
        predictions = model.predict(X_test)
        # Printing different evaluation metrics
        print( str(model.base_estimator_)[:-2] + " R2-score: ", r2_score(y_test, predictions))
        print( str(model.base_estimator_)[:-2] + " MSE: ",mean_squared_error(y_test,predictions))
        print( str(model.base_estimator_)[:-2] + " RMSE: ",np.sqrt(mean_squared_error(y_test,predictions)))
        print( str(model.base_estimator_)[:-2] + " MAE: ",mean_absolute_error(y_test, predictions))
        print('\n')
        return model

In [87]:
# Defining a model
RfR = RandomForestRegressor(max_depth=5)

In [88]:
model_eval_regression(RfR,train_encoded,y_train,test_encoded, y_test)

DecisionTreeRegressor R2-score:  0.3083761422882294
DecisionTreeRegressor MSE:  75.42279121560303
DecisionTreeRegressor RMSE:  8.684629595763024
DecisionTreeRegressor MAE:  4.163919326622861




RandomForestRegressor(max_depth=5)

## Feature Selection

In [90]:
#variance
# Fitting
sel_regr = VarianceThreshold(threshold= 0.01)
sel_regr = sel_regr.fit(train_encoded)

In [91]:
# Check wich columns have low variance
sel_regr.get_support()
# Making it a list
var_list = list(sel_regr.get_support())
# Creating a droplist
droplist_var_regr = [col[0] for col in zip(train_encoded.columns, var_list) if col[1] == False]
print(droplist_var_regr)
len(droplist_var_regr)

['RFA_2R_L', 'TCODE', 'HIT', 'MALEMILI', 'FEDGOV', 'POP901', 'POP902', 'POP903', 'POP90C4', 'POP90C5', 'ETH3', 'ETH4', 'ETH6', 'ETH7', 'ETH8', 'ETH9', 'ETH10', 'ETH11', 'ETH12', 'ETH14', 'ETH15', 'ETH16', 'AGE904', 'AGE905', 'AGE906', 'CHIL1', 'CHIL2', 'CHIL3', 'AGEC1', 'AGEC3', 'CHILC1', 'CHILC4', 'CHILC5', 'HHN2', 'HHN5', 'HHN6', 'MARR2', 'HHP2', 'DW3', 'DW7', 'DW8', 'DW9', 'HHD7', 'HHD9', 'HHD10', 'HHD12', 'ETHC4', 'ETHC6', 'HUR1', 'RHP3', 'RHP4', 'HUPA4', 'HUPA7', 'IC5', 'IC10', 'IC13', 'IC14', 'IC17', 'IC23', 'TPE2', 'TPE3', 'TPE4', 'TPE5', 'TPE6', 'TPE7', 'TPE8', 'TPE9', 'PEC1', 'TPE10', 'LFC10', 'OCC3', 'OCC4', 'OCC5', 'OCC6', 'OCC7', 'OCC8', 'OCC9', 'EIC1', 'EIC2', 'EIC3', 'EIC7', 'EIC8', 'EIC9', 'EIC10', 'EIC11', 'EIC12', 'EIC13', 'EIC14', 'EIC15', 'OEDC3', 'OEDC4', 'OEDC6', 'OEDC7', 'EC2', 'SEC1', 'SEC5', 'AFC1', 'AFC2', 'AFC3', 'AFC6', 'VC2', 'ANC1', 'ANC2', 'ANC3', 'ANC5', 'ANC6', 'ANC7', 'ANC8', 'ANC9', 'ANC10', 'ANC11', 'ANC12', 'ANC13', 'ANC14', 'ANC15', 'LSC3', 'LSC4', 

131

In [94]:
# Checking result:
# Checking result:
model_eval_regression(RfR, train_encoded.drop(droplist_var_regr, axis=1), y_train, test_encoded.drop(droplist_var_regr, axis=1))



SyntaxError: unexpected EOF while parsing (Temp/ipykernel_17272/1730560179.py, line 2)

In [95]:
# Continuing with this
train_var = train_encoded.drop(droplist_var_regr, axis = 1).copy()
test_var = test_encoded.drop(droplist_var_regr, axis = 1).copy()

## Hyperparameter search:

In [96]:
RfR = RandomForestRegressor()

In [98]:
max_depth_choices= [2,3,4,5,6,7,9,10,None]
criterion_choices = ['squared_error']
min_samples_split_choices = [1,2,5,20,50,100,200]
min_samples_leaf_choices = [2,5,20,50,100,200]
max_features_choices = ["auto", "sqrt", "log2", None, 10]



grid = {'max_depth': max_depth_choices,
               'criterion': criterion_choices,
               'min_samples_split': min_samples_split_choices,
               'min_samples_leaf': min_samples_leaf_choices,
               'max_features': max_features_choices,
               'bootstrap' : [True,False]}

In [99]:
# Grid search
from sklearn.model_selection import GridSearchCV

grid_search = GridSearchCV(estimator = RfR, param_grid = grid, cv = 6)

In [101]:
# Fit the grid search to the data
grid_search.fit(train_var, y_train)

KeyboardInterrupt: 

In [ ]:
grid_search = pickle.load(open('grid_search.p','rb'))

In [ ]:
grid_search.best_params_

## Building final Model

In [ ]:
# Setting model with selected Hyperparameters
RfR = RandomForestRegressor(min_samples_split= 50,
 min_samples_leaf = 50,
 max_features = None,
 max_depth = 6,
 criterion = 'squared_error',
 bootstrap = True)

In [ ]:
%%time
# Training model
RfR.fit(train_var, y_train)

In [ ]:
#Making Prediction
X = df_all[df_all['predicted_donate']==1].copy()
X = X.drop(['TARGET_D', 'TARGET_B', 'predicted_donate'], axis = 1)

In [ ]:
X_num   X.select_dtypes(include = np.number)
X_cat = X.select_dtypes(include = object)

X_num_scaled = pd.DataFrame(transformer.transform(X_num), columns = X_num.columns, index = X_num.index)

X_encoded = pd.DataFrame(encoder.transform(X_cat).toarray(),columns = column_name, index=X_cat.index)

X_transformed = pd.concat([X_encoded, X_num_scaled], axis = 1)

X_transformed.drop(droplist_var_regr, axis = 1, inplace = True)

In [ ]:
#predicting

In [ ]:
predictions_r = RfR.predict(X_transformed)
predictions_r